### ISSUE TITLE
Warhammer Darktide Mesh Issues

### ISSUE THREAD

**Issue by DrogonMar** [HansKristian-Work/vkd3d-proton#1298]
CPU: Ryzen 7 2700x
GPU: 6900XT (RADV, Mesa 22.1.7) [gpuinfo](http://vulkan.gpuinfo.org/displayreport.php?id=16390)
Distro: Fedora 36
Kernel: 6.0.7-200
Running Darktide with Proton GE 7-41 with all settings at high.

Darktide has issues with low quality meshes the further away from spawn you are, like when I spawn my guns scope exists and has a high quality mesh but when im 20%~ or more into the mission it no longer has a cross hair and its very blocky.

Images of the issue:
![20221117173201_1](https://user-images.githubusercontent.com/17402379/202597652-68b2acdc-c905-49d8-aaf0-a1e7c602bfc7.jpg)
![Screenshot_20221117_173416](https://user-images.githubusercontent.com/17402379/202597487-fa0a7d20-e799-4f83-a1e5-7367c97b118b.png)

**Comment by HansKristian-Work** [comment]
I played it for a while until I completed the prologue, but I couldn't reproduce anything in particular. Where would I be able to reproduce this reliably? Do we have any indication this is not a game issue? Mesh LOD selection tends to be more on game side than API side. There might be memory pressure being queried from DXGI that could influence this, but I doubt a 6900xt would have any issues ...

**Comment by HansKristian-Work** [comment]
I think I might have seen this randomly on some meshes actually, just not the gun. Will have to investigate if this can happen on native as well.

**Comment by DrogonMar** [comment]
> I played it for a while until I completed the prologue (at least where you get to the hub for the first time), but I couldn't reproduce anything in particular. Where would I be able to reproduce this reliably? Do we have any indication this is not a game issue? Mesh LOD selection tends to be more on game side than API side. There might be memory pressure being queried from DXGI that could influence this, but I doubt a 6900xt would have any issues ...

Yeah its a very weird issue sometimes it wont happen but a lot of times it will and only on select meshes, the gun on your first person camera seems to happen a lot more commonly.

**Comment by Ozbourne** [comment]
Archcraft - 6.0.9-272-tkg-cfs
Intel i7-4960X
NVIDIA GeForce GTX 1070 Ti - 525.60.11
Proton experimental-7.0-20221115

Happens very often with shotguns, alt tabbing seems to fix it, temporarily at least.
Running all settings low/off with fsr 2.0 balanced.

![darktidelodshotgun](https://user-images.githubusercontent.com/42701499/205401932-a149a715-73c5-4131-84fd-2f66f1e7feed.png)

**Comment by DrogonMar** [comment]
I haven't played the game to see if this patch fixes it but sounds very much like this issue, I will report back if this has fixed it when I play the game later today.
### **Engine**

- Multiple fixes to prevent GPU Hangs
- Fixes to address network disconnects
- Raytracing now works on AMD RX 6/7000 cards.
- **Visual glitches around weapons and in levels for users of AMD cards has been fixed**
- Fixed a crash that sometimes happened to players after watching a video cutscene

Its at the bottom of this [patch note](https://store.steampowered.com/news/app/1361210/view/3613606722095734807?l=english)

**Comment by DrogonMar** [comment]
After playing two missions my gun scope seems to be fixed but mesh issues in the world are still present.
In this one of the wheels is fine while the other one is just bad.

![20221216124307_1](https://user-images.githubusercontent.com/17402379/208191031-307420f3-f350-4829-98e1-8eb2807bdc4d.jpg)

This isn't pertaining to this issue but just gonna bring it up anyway, in some patch to the game made player meshs have this weird black outline and it seems to be distance based, it can also happen to some things in the world like flags.
You can see this in my first screenshot on Yordo and how his skin is just black.
<details>
<summary>Images</summary>

![image](https://user-images.githubusercontent.com/17402379/208191423-16574adc-1727-48cd-9cc9-ccae591309b8.png)
![image](https://user-images.githubusercontent.com/17402379/208191498-531a0916-0ee4-427c-a29d-4dde0b22d618.png)

</details>

**Comment by Thermatix** [comment]
This is still an issue for me.

<details><summary>Computer Information</summary>

```
Manufacturer: ASUSTeK COMPUTER INC. (Actually I built the computer)
Model: ROG STRIX B650E-I GAMING WIFI
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Ryzen 5 7600X 6-Core Processor
CPU Family: 0x19
CPU Model: 0x61
CPU Stepping: 0x2
CPU Type: 0x0
Speed: 5453 MHz
12 logical processors
6 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Supported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Supported
AVX512VNNI: Supported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
"EndeavourOS Linux" (64 bit)
Kernel Name: Linux
Kernel Version: 6.5.5-zen1-1-zen
X Server Vendor: The X.Org Foundation
X Server Release: 12101008
X Window Manager: Xfwm4
Steam Runtime Version: steam-runtime_0.20230801.56012
Video Card:
Driver: AMD AMD Radeon RX 7900 XTX (gfx1100, LLVM 16.0.6, DRM 3.54, 6.5.5-zen1-1-zen)
Driver Version: 4.6 (Compatibility Profile) Mesa 23.2.1-arch1.1
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 143 Hz
VendorID: 0x1002
DeviceID: 0x744c
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20.94" x 11.97" (24.09" diag), 53.2cm x 30.4cm (61.2cm diag)
Primary VRAM: 24576 MB
Sound card:
Audio device: ATI R6xx HDMI
Memory:
RAM: 31836 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
LANG: en_GB.UTF-8
Total Hard Disk Space Available: 319390 MB
Largest Free Hard Disk Block: 226541 MB
Storage:
Number of SSDs: 2
SSD sizes: 0B,0B
Number of HDDs: 0
Number of removable drives: 0
```
</details>

**Comment by Billli11** [comment]
look like the mesh streaming issue. [known issue](https://forums.fatsharkgames.com/t/low-detail-models-mesh-streaming-broken/57842)

Change line `57` to

    	disable = true


in `steamapps\common\Warhammer 40,000 DARKTIDE\bundle\application_settings\settings_common.ini` should fix the problem.
