### ISSUE TITLE
Star Wars outlaws Crashes

### ISSUE THREAD

**Issue by ryzendew** [HansKristian-Work/vkd3d-proton#2092]
Please describe your issue as accurately as possible. Include screenshots or videos if relevant

### Software information
Name of the game, settings used etc.

### System information
- GPU: RTX 4070 / 5700XT
- Driver:560.35.03
- Wine version: proton GE 9-11
- VKD3D-Proton version: 2.13
[kernel_logs.txt](https://github.com/user-attachments/files/16769743/kernel_logs.txt)
[vkd3d log](https://github.com/user-attachments/files/16769744/vkd3d.log)

**Comment by ryzendew** [comment]
if you need a more detailed log let me know how please

**Comment by TheWiseNoob** [comment]
Also experiencing a crash. Mine on launch. Black screen shots for a moment than then crashes. Is that what happens to you? I'm using a 4090.

**Comment by Saancreed** [comment]
@ryzendew I have no idea how you did this but your so-called vkd3d log doesn't have a single line of message from vkd3d-proton so it's actually fairly useless.

Anyway, some extra details, at least for Nvidia case:

* vkd3d-proton handles the driver a compute pipeline that the driver refuses to compile:

```
NVVM compilation failed: 1
err:vkd3d-proton:vkd3d_create_compute_pipeline: Failed to create Vulkan compute pipeline, hr 0.
err:vkd3d-proton:vkd3d_create_compute_pipeline:   Root signature: 2dfc82bcd6ff54b7
err:vkd3d-proton:vkd3d_create_compute_pipeline:   Shader: 60dd17e7848184b2.
fixme:vkd3d-proton:hresult_from_vk_result: Unhandled VkResult -13.
```

* A pruned fossilize database that reproduces this issue (captured with `VKD3D_DISABLE_EXTENSIONS=VK_EXT_depth_bias_control,VK_NV_raw_access_chains` because otherwise Foz complained about unsupported structures/capabilities) is here: [Outlaws.6a67da392932e15c.0xbed8e2535534026d.foz.zip](https://github.com/user-attachments/files/16786510/Outlaws.6a67da392932e15c.0xbed8e2535534026d.foz.zip)

* Replaying this database with `--spirv-val` reports validation errors:

```
Fossilize ERROR: spirv-val: [VUID-StandaloneSpirv-Base-04781] Expected 32-bit int type for Base operand: BitCount
  %688 = OpBitCount %uint %687

Fossilize WARN: Failed to validate SPIR-V module: DB334CA09D765CC2, skipping!
```

… which suggests dxil-spirv is mistranslating this shader, so DXIL in question is attached here: [60dd17e7848184b2..zip](https://github.com/user-attachments/files/16786535/60dd17e7848184b2.zip)

However, it's likely this isn't the only issue because RADV chokes later on another invalid SPIR-V as reported here: https://github.com/HansKristian-Work/dxil-spirv/issues/199

Afaik only AMDVLK is resilient enough to get in-game with current vkd3d-proton and dxil-spirv.

**Comment by TheWiseNoob** [comment]
Thanks for looking into this!

What likely has to be patched to fix this problem? The game? The driver? vkd3d-proton? Something else?

**Comment by mbriar** [comment]
Most likely vkd3d-proton/dxil-spirv if it generates invalid spirv.

**Comment by vleeuwenmenno** [comment]
Not sure where to report this, but I'm running a `AMD 7900 XTX` and using either `soda`, `proton`, `proton-ge` or `wine-get` the game boots up until I load my save game/start a new one. Then everything freezes on loading menu and the display manager crashes requiring a full reboot to be able to recover any responsiveness.

**Comment by Blisto91** [comment]
@vleeuwenmenno hi there. I have created a mesa issue for the hang problem https://gitlab.freedesktop.org/mesa/mesa/-/issues/11790

**Comment by HansKristian-Work** [comment]
Please try https://github.com/HansKristian-Work/vkd3d-proton/pull/2096.

**Comment by vleeuwenmenno** [comment]
@HansKristian-Work After compiling and moving it into lutris it now loads into the game without issues.

It runs pretty well on my 7900 XTX but there's one issue still, I am not entirely sure what it is and if I could help sending in a log or something but if I set my raytraced contact shadows setting to ultra the game crashes. With all the other settings it does not crash.

**Comment by TheWiseNoob** [comment]
> @HansKristian-Work After compiling and moving it into lutris it now loads into the game without issues. (So #2096 does indeed fix the issue)
> 
> It runs pretty well on my 7900 XTX but there's one issue still, I am not entirely sure what it is and if I could help sending in a log or something but if I set my raytraced contact shadows setting to ultra the game crashes. With all the other settings it does not crash.

@vleeuwenmenno By "#RTFM" do you mean you used the README of this repo? Might give compiling a try.

**Comment by sergeykern** [comment]
Hi,

many thanks for the fix. 

I got it working after some tinkering (building, etc.). It runs quite well under wayland on my HP Omen 16 (R7 7840HS, RTX 4060). For some reasons it refused to start the game. I fixed it by copying the "Ubisoft Game Launcher" folder from AppData>Local from my Windows 11 installment to the corresponding folder. Next problem was, that the game would freeze on resuming save. I just copied the folder "ShaderByteCode" from Documents>My Games>Outlaws from the Windows 11 environment.

FPS are a little higher, I'd say 10 - 15 FPS more (baseline like 100 FPS under Windows 11). However, frame times seem to be better under Windows and graphics, too (DLSS3 + FG vs FSR3 + FG). Maybe it's just shader caching and will get better over time. I will try to run under X11, too.

Greetings

**Comment by makulski** [comment]
> > > Please try #2096.
> > 
> > 
> > Hi,
> > many thanks for the fix.
> > I got it working after some tinkering (building, etc.). It runs quite well under wayland on my HP Omen 16 (R7 7840HS, RTX 4060). For some reasons it refused to start the game. I fixed it by copying the "Ubisoft Game Launcher" folder from AppData>Local from my Windows 11 installment to the corresponding folder. Next problem was, that the game would freeze on resuming save. I just copied the folder "ShaderByteCode" from Documents>My Games>Outlaws from the Windows 11 environment.
> > FPS are a little higher, I'd say 10 - 15 FPS more (baseline like 100 FPS under Windows 11). However, frame times seem to be better under Windows and graphics, too (DLSS3 + FG vs FSR3 + FG). Maybe it's just shader caching and will get better over time. I will try to run under X11, too.
> > Greetings
> > Edit:
> > I got the initial problems back again (with "product cannot be activated" at start and with the freezing on save load) even on Windows. I fixed it hopefully for longer by just reinstalling Ubisoft Connect in a different wine prefix. Still have to fix it on Windows. I guess Denuvo just checked my tinkering changes and disabled the game smh. Anyway game is now running on Wine 9.9, Vsync-off (with goverlay), FSR3+FG with a good frame rate.
> > I'm happy right now, wanted to ditch Windows 11 anyway. Only thing that I'm missing is the better upscaling quality with DLSS (I know I can activate it under Linux but without frame gen).
> 
> Hello @sergeykern
> 
> If you have time, could you give a bit of details of how you managed to make it run ? I have successfully build vkd3d-proton from this repo and how I have a bunch of files that I don't know exactly what to do 🤔
> 
> Thanks in advance !

I am also asking nicely for some ELI5 directions, thanks :)

**Comment by TheWiseNoob** [comment]
> > > > Please try #2096.
> > > 
> > > 
> > > Hi,
> > > many thanks for the fix.
> > > I got it working after some tinkering (building, etc.). It runs quite well under wayland on my HP Omen 16 (R7 7840HS, RTX 4060). For some reasons it refused to start the game. I fixed it by copying the "Ubisoft Game Launcher" folder from AppData>Local from my Windows 11 installment to the corresponding folder. Next problem was, that the game would freeze on resuming save. I just copied the folder "ShaderByteCode" from Documents>My Games>Outlaws from the Windows 11 environment.
> > > FPS are a little higher, I'd say 10 - 15 FPS more (baseline like 100 FPS under Windows 11). However, frame times seem to be better under Windows and graphics, too (DLSS3 + FG vs FSR3 + FG). Maybe it's just shader caching and will get better over time. I will try to run under X11, too.
> > > Greetings
> > > Edit:
> > > I got the initial problems back again (with "product cannot be activated" at start and with the freezing on save load) even on Windows. I fixed it hopefully for longer by just reinstalling Ubisoft Connect in a different wine prefix. Still have to fix it on Windows. I guess Denuvo just checked my tinkering changes and disabled the game smh. Anyway game is now running on Wine 9.9, Vsync-off (with goverlay), FSR3+FG with a good frame rate.
> > > I'm happy right now, wanted to ditch Windows 11 anyway. Only thing that I'm missing is the better upscaling quality with DLSS (I know I can activate it under Linux but without frame gen).
> > 
> > 
> > Hello @sergeykern
> > If you have time, could you give a bit of details of how you managed to make it run ? I have successfully build vkd3d-proton from this repo and how I have a bunch of files that I don't know exactly what to do 🤔
> > Thanks in advance !
> 
> I am also asking nicely for some ELI5 directions, thanks :)
 
@makulski @N0ciple 

I just got it working with Lutris! Works really well. Make sure to set Contact Shadows to Low for raytracing.

I don't know if this the best way to it, but I'll explain how I did it.

1. Get Lutris. I used Lutris from the official Arch repos.
2. Install Ubisoft Connect via Lutris' option on the sidebar, login, and install Outlaws.
3. Now you need to replace the two dlls for vkd3d for both x86 and x64
4. Since this patch is merged into the master branch, pull master
5. Pull master with `git clone --recursive https://github.com/HansKristian-Work/vkd3d-proton`
6. Change to the directory you just pulled with `cd vkd3d-proton`
7. Build in your current directory with `./package-release.sh master ./ --no-package`
8. There's a new folder in your current folder called `vkd3d-proton-master`. Copy both dlls from the x86 and x64 folders into the respective Lutris folders for your chosen vkd3d-proton folders. For example, mine were in /home/YOU_HOME_DIRECTORY/.local/share/lutris/runtime/vkd3d/v2.12 with Lutris on Arch. I'm using the main Arch Lutris build, not a Flatpak if it exists.
9. Make sure to replace YOUR_HOME_DIRECTORY with your home directory's name.

**Comment by realbardia** [comment]
Hi
I got it working on steamdeck (amd) using GE-Proton9.11 (using non-steam app) and that patch.
Just build and copy two dlls (d3d12.dll and d3d12core.dll) to `$HOME/.local/share/Steam/compatibilitytools.d/GE-Proton9-11/files/lib64/wine/vkd3d-proton/`
I tested It on my steamdeck and it runs without any issue. But on my PC (Debian 12 and Nvidia 3080 RTX) It crashes after game loaded.

**Comment by SiriusStevas** [comment]
> Hi I got it working on steamdeck (amd) using GE-Proton9.11 (using non-steam app) and that patch. Just build and copy two dlls (d3d12.dll and d3d12core.dll) to `$HOME/.local/share/Steam/compatibilitytools.d/GE-Proton9-11/files/lib64/wine/vkd3d-proton/` I tested It on my steamdeck and it runs without any issue. But on my PC (Debian 12 and Nvidia 3080 RTX) It crashes after game loaded.

I don't know if it's allowed to ask, but can you please send that two dlls? I've spent many hours trying to install everything required for the build with no success. Just want to play Outlaws bruh

**Comment by makulski** [comment]
> > > > > Please try #2096.
> > > > 
> > > > 
> > > > Hi,
> > > > many thanks for the fix.
> > > > I got it working after some tinkering (building, etc.). It runs quite well under wayland on my HP Omen 16 (R7 7840HS, RTX 4060). For some reasons it refused to start the game. I fixed it by copying the "Ubisoft Game Launcher" folder from AppData>Local from my Windows 11 installment to the corresponding folder. Next problem was, that the game would freeze on resuming save. I just copied the folder "ShaderByteCode" from Documents>My Games>Outlaws from the Windows 11 environment.
> > > > FPS are a little higher, I'd say 10 - 15 FPS more (baseline like 100 FPS under Windows 11). However, frame times seem to be better under Windows and graphics, too (DLSS3 + FG vs FSR3 + FG). Maybe it's just shader caching and will get better over time. I will try to run under X11, too.
> > > > Greetings
> > > > Edit:
> > > > I got the initial problems back again (with "product cannot be activated" at start and with the freezing on save load) even on Windows. I fixed it hopefully for longer by just reinstalling Ubisoft Connect in a different wine prefix. Still have to fix it on Windows. I guess Denuvo just checked my tinkering changes and disabled the game smh. Anyway game is now running on Wine 9.9, Vsync-off (with goverlay), FSR3+FG with a good frame rate.
> > > > I'm happy right now, wanted to ditch Windows 11 anyway. Only thing that I'm missing is the better upscaling quality with DLSS (I know I can activate it under Linux but without frame gen).
> > > 
> > > 
> > > Hello @sergeykern
> > > If you have time, could you give a bit of details of how you managed to make it run ? I have successfully build vkd3d-proton from this repo and how I have a bunch of files that I don't know exactly what to do 🤔
> > > Thanks in advance !
> > 
> > 
> > I am also asking nicely for some ELI5 directions, thanks :)
> 
> @makulski @N0ciple
> 
> I just got it working with Lutris! Works really well. Make sure to set Contact Shadows to Low for raytracing. I'm using a 4090.
> 
> I don't know if this the best way to it, but I'll explain how I did it.
> 
>     1. Get Lutris. I used Lutris from the official Arch repos.
> 
>     2. Install Ubisoft Connect via Lutris' option on the sidebar, login, and install Outlaws.
> 
>     3. Now you need to replace the two dlls(d3d12.dll and d3d12core.dll) for vkd3d-proton for both x86 and x64
> 
>     4. Since this patch is merged into the master branch, pull master
> 
>     5. Pull master with `git clone --recursive https://github.com/HansKristian-Work/vkd3d-proton`
> 
>     6. Change to the directory you just pulled with `cd vkd3d-proton`
> 
>     7. Build in your current directory with `./package-release.sh master ./ --no-package`
> 
>     8. There's a new folder in your current folder called `vkd3d-proton-master`. Copy both dlls from the x86 and x64 folders into the respective Lutris folders for your chosen vkd3d-proton folders. For example, mine were in `/home/YOUR_HOME_DIRECTORY/.local/share/lutris/runtime/vkd3d/v2.12` with Lutris on Arch. I'm using the main Arch Lutris build, not a Flatpak if it exists.
> 
>     9. Make sure to replace YOUR_HOME_DIRECTORY with your home directory's name.
> 
>     10. Should be playable now!

Thank you Good Sir - it worked perfectly. Game now runs almost flawlessly on my 4080 (this new RTX thing is borked).

Bests!

**Comment by Surf-Wax** [comment]
> > > > > Please try #2096.
> > > > 
> > > > 
> > > > Hi,
> > > > many thanks for the fix.
> > > > I got it working after some tinkering (building, etc.). It runs quite well under wayland on my HP Omen 16 (R7 7840HS, RTX 4060). For some reasons it refused to start the game. I fixed it by copying the "Ubisoft Game Launcher" folder from AppData>Local from my Windows 11 installment to the corresponding folder. Next problem was, that the game would freeze on resuming save. I just copied the folder "ShaderByteCode" from Documents>My Games>Outlaws from the Windows 11 environment.
> > > > FPS are a little higher, I'd say 10 - 15 FPS more (baseline like 100 FPS under Windows 11). However, frame times seem to be better under Windows and graphics, too (DLSS3 + FG vs FSR3 + FG). Maybe it's just shader caching and will get better over time. I will try to run under X11, too.
> > > > Greetings
> > > > Edit:
> > > > I got the initial problems back again (with "product cannot be activated" at start and with the freezing on save load) even on Windows. I fixed it hopefully for longer by just reinstalling Ubisoft Connect in a different wine prefix. Still have to fix it on Windows. I guess Denuvo just checked my tinkering changes and disabled the game smh. Anyway game is now running on Wine 9.9, Vsync-off (with goverlay), FSR3+FG with a good frame rate.
> > > > I'm happy right now, wanted to ditch Windows 11 anyway. Only thing that I'm missing is the better upscaling quality with DLSS (I know I can activate it under Linux but without frame gen).
> > > 
> > > 
> > > Hello @sergeykern
> > > If you have time, could you give a bit of details of how you managed to make it run ? I have successfully build vkd3d-proton from this repo and how I have a bunch of files that I don't know exactly what to do 🤔
> > > Thanks in advance !
> > 
> > 
> > I am also asking nicely for some ELI5 directions, thanks :)
> 
> @makulski @N0ciple
> 
> I just got it working with Lutris! Works really well. Make sure to set Contact Shadows to Low for raytracing. I'm using a 4090.
> 
> I don't know if this the best way to it, but I'll explain how I did it.
> 
> 1. Get Lutris. I used Lutris from the official Arch repos.
> 2. Install Ubisoft Connect via Lutris' option on the sidebar, login, and install Outlaws.
> 3. Now you need to replace the two dlls(d3d12.dll and d3d12core.dll) for vkd3d-proton for both x86 and x64
> 4. Since this patch is merged into the master branch, pull master
> 5. Pull master with `git clone --recursive https://github.com/HansKristian-Work/vkd3d-proton`
> 6. Change to the directory you just pulled with `cd vkd3d-proton`
> 7. Build in your current directory with `./package-release.sh master ./ --no-package`
> 8. There's a new folder in your current folder called `vkd3d-proton-master`. Copy both dlls from the x86 and x64 folders into the respective Lutris folders for your chosen vkd3d-proton folders. For example, mine were in `/home/YOUR_HOME_DIRECTORY/.local/share/lutris/runtime/vkd3d/v2.12` with Lutris on Arch. I'm using the main Arch Lutris build, not a Flatpak if it exists.
> 9. Make sure to replace YOUR_HOME_DIRECTORY with your home directory's name.
> 10. Should be playable now!

Instead of cloning the repo and building, you can go to the releases - https://github.com/HansKristian-Work/vkd3d-proton/releases - and download the `vkd3d-proton-2.13.tar.zst` file, extract it, and inside are the two .dll files to copy

**Comment by Blisto91** [comment]
> Instead of cloning the repo and building, you can go to the releases - https://github.com/HansKristian-Work/vkd3d-proton/releases - and download the `vkd3d-proton-2.13.tar.zst` file, extract it, and inside are the two .dll files to copy

These current fixes aren't included in any stable releases.
Pre built versions of master can be found here https://github.com/HansKristian-Work/vkd3d-proton/actions/workflows/artifacts.yml?query=branch%3Amaster
Note that there is still a known issue in regards to the RT options https://github.com/HansKristian-Work/dxil-spirv/issues/199

**Comment by realbardia** [comment]
> > Hi I got it working on steamdeck (amd) using GE-Proton9.11 (using non-steam app) and that patch. Just build and copy two dlls (d3d12.dll and d3d12core.dll) to `$HOME/.local/share/Steam/compatibilitytools.d/GE-Proton9-11/files/lib64/wine/vkd3d-proton/` I tested It on my steamdeck and it runs without any issue. But on my PC (Debian 12 and Nvidia 3080 RTX) It crashes after game loaded.
> 
> I don't know if it's allowed to ask, but can you please send that two dlls? I've spent many hours trying to install everything required for the build with no success. Just want to play Outlaws bruh

I built it on Debian 12 using below commands
```
sudo apt-get install meson  glslang-tools glslang-dev mingw-w64-x86-64-dev libwine-dev
./package-release.sh master ./package --no-package
```
and create a release on the below repository:
https://github.com/realbardia/vkd3d-proton/releases/tag/starwars_outlaws

**Comment by SiriusStevas** [comment]
> > > Hi I got it working on steamdeck (amd) using GE-Proton9.11 (using non-steam app) and that patch. Just build and copy two dlls (d3d12.dll and d3d12core.dll) to `$HOME/.local/share/Steam/compatibilitytools.d/GE-Proton9-11/files/lib64/wine/vkd3d-proton/` I tested It on my steamdeck and it runs without any issue. But on my PC (Debian 12 and Nvidia 3080 RTX) It crashes after game loaded.
> > 
> > 
> > I don't know if it's allowed to ask, but can you please send that two dlls? I've spent many hours trying to install everything required for the build with no success. Just want to play Outlaws bruh
> 
> I built it on Debian 12 using below commands
> 
> ```
> sudo apt-get install meson  glslang-tools glslang-dev mingw-w64-x86-64-dev libwine-dev
> ./package-release.sh master ./package --no-package
> ```
> 
> and create a release on the below repository: https://github.com/realbardia/vkd3d-proton/releases/tag/starwars_outlaws

Thank you very much!

**Comment by realbardia** [comment]
I also tested It using Lutris and new dlls on my pc (Nvidia 3080 RTX) and now It works fine.
Thanks to @TheWiseNoob

**Comment by sergeykern** [comment]
It worked well for a few minutes but now when I load a savegame it would crash. I could start a new game after deleting the caches but I cannot resume the game. I added a log here.
[log.txt](https://github.com/user-attachments/files/16824844/log.txt)

**Comment by TheWiseNoob** [comment]
Every time I reload the game it will lock up on the loading into game screen unless I delete my /home/YOU_HOME_FOLDER/Games/ubisoft-connect/GLCache folder before loading the game.

**Comment by sergeykern** [comment]
@TheWiseNoob Many, many thanks. That did the trick! I could even load my 2 hours save from Windows. A little bit inconvenient but it's ok for now.

**Comment by SiriusStevas** [comment]
Okay, I give up. Have tried to launch this game on steam deck for 2 days straight and nothing works. The game stopped crushing with the new dlls but it just freezes on the loading screen. Lame

**Comment by sergeykern** [comment]
Does anyone know what to do if the game cannot be started with message "This product cannot be activated right now". I think it's Denuvo related. I mean I just changed wine version a few times and now it thinks that the hardware configuration changed or smth like that. Formerly I reinstalled Ubisoft and it was fixed (however that could just be coincidence bc some time passed). 

It's tedious right now. Got the game on 28/08 and could only play for two hours. Even on Windows it would crash after a while and I got the "game not activated" error there, too. I mean I could bootup Windows again and there some time has passed and will maybe work again (and there I can do DLSS+FG again) but I want to use EndevourOS on daily bases.

I hope the game will be c***ed soon as these new games (bugs, bad performance) and anti-consumer practices (Denuvo) are unacceptable for customers.

**Comment by sergeykern** [comment]
> Okay, I give up. Have tried to launch this game on steam deck for 2 days straight and nothing works. The game stopped crushing with the new dlls but it just freezes on the loading screen. Lame

Try the fix of TheWiseNoob https://github.com/HansKristian-Work/vkd3d-proton/issues/2092#issuecomment-2322899347. This should get you in-game (assuming everthing else is setup fine).

**Comment by SiriusStevas** [comment]
> Does anyone know what to do if the game cannot be started with message "This product cannot be activated right now". I think it's Denuvo related. I mean I just changed wine version a few times and now it thinks that the hardware configuration changed or smth like that. Formerly I reinstalled Ubisoft and it was fixed (however that could just be coincidence bc some time passed).
> 
> It's tedious right now. Got the game on 28/08 and could only play for two hours. Even on Windows it would crash after a while and I got the "game not activated" error there, too. I mean I could bootup Windows again and there some time has passed and will maybe work again (and there I can do DLSS+FG again) but I want to use EndevourOS on daily bases.
> 
> I hope the game will be c***ed soon as these new games (bugs, bad performance) and anti-consumer practices (Denuvo) are unacceptable for customers.

As far as I know, Denuvo gives 5 activations for 24 hours per game. If you launch game with different proton/wine it detect it as an instalation on a new device, taking 1 of 5 activation. After all of the activations used — game become unaviable, until there is 1 free activation. 
Basically, if you firstly launched game at 12:00 and got denuvo error at 16:00, you'll be able to run game on only one proton/wine configuration at 12:00 the next day.

It absolutely sucks, but you can't do anything, besides waiting, I'm sorry

**Comment by SiriusStevas** [comment]
> > Okay, I give up. Have tried to launch this game on steam deck for 2 days straight and nothing works. The game stopped crushing with the new dlls but it just freezes on the loading screen. Lame
> 
> Try the fix of TheWiseNoob [#2092 (comment)](https://github.com/HansKristian-Work/vkd3d-proton/issues/2092#issuecomment-2322899347). This should get you in-game (assuming everthing else is setup fine).

Thanks but didn't work for me. Guess I'll wait for the more casual fix

**Comment by vleeuwenmenno** [comment]
I've been playing since the initial fix was available. No issues here, except for the RT contact shadows only working on low settings. For reference: `Ubuntu 24.04 LTS w/ 6.8.0-41-generic w/ Ryzen 3900X - 7900 XTX - 64GB DDR4 (x11 w/ gdm - cinnamon)`

I don't have my Steam Deck with me at the moment so cannot reproduce it atm but I'm able to help out if you're deseperate enough LOL. You can contact on `vkd3d-proton-2092.handwork599@passmail.net` to share Discord/Teamspeak and we can have a look.

Also please be aware not everyone has been able to test it out yet since this game specifically is only fully  released yesterday and not every developer has 100+ euro to spend on a gamble from Ubisoft 😅

**Comment by TheWiseNoob** [comment]
> I've been playing since the initial fix was available. No issues here, except for the RT contact shadows only working on low settings. For reference: `Ubuntu 24.04 LTS w/ 6.8.0-41-generic w/ Ryzen 3900X - 7900 XTX - 64GB DDR4 (x11 w/ gdm - cinnamon)`
> 
> I don't have my Steam Deck with me at the moment so cannot reproduce it atm but I'm able to help out if you're deseperate enough LOL. You can contact on `vkd3d-proton-2092.handwork599@passmail.net` to share Discord/Teamspeak and we can have a look.
> 
> Also please be aware not everyone has been able to test it out yet since this game specifically is only fully released yesterday and not every developer has 100+ euro to spend on a gamble from Ubisoft 😅

@vleeuwenmenno 

You can play the the most expensive version of the game with Ubisoft+,  which is $18.99/month. That's what I did.

**Comment by sergeykern** [comment]
> Every time I reload the game it will lock up on the loading into game screen unless I delete my /home/YOU_HOME_FOLDER/Games/ubisoft-connect/GLCache folder before loading the game.

I fixed that by setting the env variable "libglesv2" to "d". It isn't crashing as often right now as it would before (could play for over half an hour before it crashed - big improvement -.-). This will disable the GLCache(ing) and wouldn't create the folder and files. This is also the default option if you setup Ubisoft Connect under Lutris using the login button.

Also what I experienced is that reflex and DXDI should be disabled otherwise it will crash. I'm using Wine 9.10. Does anyone know what the best Lutris settings are? I don't want to change settings so often bc Denuvo won't let me play if it detects system changes. Another thing is that you if you set frame limit in gOverlay it will stutter like hell for me. Using the in-game-limiter is possible but only if using no frame-gen (maybe only with DLSS enabled Idk exactly anymore).

**Comment by Zeabyte** [comment]
I have disabled the GLCache using the environment variable `__GL_SHADER_DISK_CACHE=0` but my game still freezes indefinitely in the loading screen. No Wine or VKD3D errors.

**Comment by Blisto91** [comment]
Put Ray Tracing options on their lowest if you haven't already.

**Comment by Zeabyte** [comment]
> Put Ray Tracing options on their lowest if you haven't already.

I have. Everything is either off or on the lowest settings. No luck so far.

**Comment by Blisto91** [comment]
There is still at least one known dxil-spirv issue (maybe more but not sure atm). Will likely get a look at here after the weekend

**Comment by Crejan** [comment]
Somehow it does not work for me with the DLL fix. every time.
using:
- intel 12900k with RTX 4090
- recently updated arch linux with lutris from pacman
- Nvidia driver 560.35.03
- GE-Proton latest
- VKD3D DLL's build from https://github.com/HansKristian-Work/vkd3d-proton master HEAD (7091b2c853092f193b8999e355bad32c7d5040b4)

still getting `NVVM compilation failed: 1` even if I remove the GLCache every time

**Comment by Zeabyte** [comment]
After about 15 game starts, I have been able to load a game without freezing 3 times. No idea what this means. Switching graphics quality settings will freeze the game.

**Comment by napcos** [comment]
The game is fixed with Proton GE-12
But Constact shadows ray tracing is only low setting, change this option crash the game

**Comment by joshleblanc** [comment]
Can confirm it's working on GEproton 9-12

**Comment by sergeykern** [comment]
Sometimes it helps to delete vulkan caches in game folder and/or cut "wine-prefix > User > Documents > My Games > Outlaws > ShaderByteCode+ShaderCache". Make sure to copy/cut it somewhere. You'll maybe need it again. Then start game. Either it will load your save or not. 

If it doesn't copy those folder back to Outlaws-Documents-folder but do not overwrite. This way you'd have the latest changes to those files, the newly generated files (which failed previously) and your old files that maybe loaded again at some point in time. 

Yeah, still crashes for me sometimes. I'm using GEproton 9-12 now, with this vkd3d-master.

**Comment by SiriusStevas** [comment]
Can confirm — the game works on Steam Deck with GEProton 9-12. Finally was able to get to the gameplay itself. It's glitchy, hardly playable, crushes after ±30 minutes, but still it's a great progress. I am already happy with that lol

**Comment by YuGi-0** [comment]
It crashes for me after the first message. Even with the DLLs built from the master branch.  I have tried it on both bottles and lutris. 

I'm on:
- Arch Linux.
-  RTX 3080.
- nvidia-open 560.35.03-2 driver (same happens with the proprietary driver).

**Comment by D2ans0** [comment]
Fixed it for me, I'm on:
NixOS
RTX 3060Ti
Nvidia 560.35.03 driver

Running it via Bottles, with soda-9.0-1

**Comment by Blisto91** [comment]
Try again with latest master https://github.com/HansKristian-Work/vkd3d-proton/actions/runs/10681015079

Also if you have crashes please post logs

**Comment by realbardia** [comment]
> Try again with latest master https://github.com/HansKristian-Work/vkd3d-proton/actions/runs/10681015079
> 
> Also if you have crashes please post logs

Built and tested on Debian 12 + Nvidia 3080 RTX, some time works fine, some times stop working on loading.
Sometimes even on High graphic settings game loaded successfully. Some times even on lowest possible settings not loaded.
I tried delete proton cache files and test again, But same happened.

I attached two logs for failed and successful:
[starwars-failed.log](https://github.com/user-attachments/files/16853462/starwars-failed.log)
[starwars-successfull.log](https://github.com/user-attachments/files/16853470/starwars-successfull.log)

**Comment by Zeabyte** [comment]
> > Try again with latest master https://github.com/HansKristian-Work/vkd3d-proton/actions/runs/10681015079
> > Also if you have crashes please post logs
> 
> Built and tested on Debian 12 + Nvidia 3080 RTX, some time works fine, some times stop working on loading. Sometimes even on High graphic settings game loaded successfully. Some times even on lowest possible settings not loaded. I tried delete proton cache files and test again, But same happened.
> 
> I attached two logs for failed and successful: [starwars-failed.log](https://github.com/user-attachments/files/16853462/starwars-failed.log) [starwars-successfull.log](https://github.com/user-attachments/files/16853470/starwars-successfull.log)

I have exactly the same problem on Fedora 40 + Nvidia RTX 3070 with VKD3D built just hours ago and Wine 9.15. When loading a save file that is somewhere in space, the game will load 100% of the time perfectly and fast. I can even go to the highest settings possible and play perfectly in space (even highest ray tracing). But then returning to a planet will almost always freeze the game (circa 80% of the time, 100% of the time on highest settings). Loading a save file from a planet has about a 90% chance of freezing the game on initial load.

**Comment by Blisto91** [comment]
Thank you. The racy or random freeze/crash is being poked at now.

**Comment by HansKristian-Work** [comment]
For GPU hangs, we need breadcrumb traces to have any hope of narrowing it down.

**Comment by revan1611** [comment]
I managed to fix game freezing/crashing, but you ain't gonna like it bros...

Apparently, the game has RT always on in graphics settings, which causes the game to freeze/crash after some time period or in some levels. 

If you disable RT in `drive_c/users/USER/Documents/My Games/Outlaws/graphic settings.cfg` and set `rtenabled` from `true` to `false`, the game won't crash/freeze anymore, plus FPS skyrockets. But... 

The entire game becomes bright, cutscenes bleached, like all post-processing and shaders become disabled. 

Check this video for comparison: https://www.youtube.com/watch?v=c1AtdtEMj-8&t=292s

It appears that devs at Ubisoft forgot how to make scene lightning and post-process and put it all on RT.

**Comment by IroAlexis** [comment]
> It appears that devs at Ubisoft forgot how to make scene lightning and post-process and put it all on RT.

He seems that Outlaws and Avatar are games that use RT only... There are not rasterization path so what you explain is expected behavior when disable rt...

**Comment by revan1611** [comment]
> > It appears that devs at Ubisoft forgot how to make scene lightning and post-process and put it all on RT.
> 
> He seems that Outlaws and Avatar are games that use RT only... There are not rasterization path so what you explain is expected behavior when disable rt...

Well, it narrows down the issue anyways. RT is the main problem that prohibits from playing this game without crashes. With RT on I'm still not able to pass through the Club section, even with just released proton-ge-9.13.

**Comment by tajeraich** [comment]
> > It appears that devs at Ubisoft forgot how to make scene lightning and post-process and put it all on RT.
> 
> He seems that Outlaws and Avatar are games that use RT only... There are not rasterization path so what you explain is expected behavior when disable rt...

From what I understand, the game uses software ray tracing as a fallback for GPUs that don't support hardware ray tracing. I don't know if this kicks in when you have it set to "low" or if it's actually only available on older cards. Is there a way to disable RT on RDNA2 or RDNA3 GPUS, for example, to test this? I know it used to be disabled by default in RADV when it was still being tested. Is there a way to disable it to see how the fallback performs?

**Comment by schlatrice** [comment]
> > > > > Please try #2096.
> > > > 
> > > > 
> > > > Hi,
> > > > many thanks for the fix.
> > > > I got it working after some tinkering (building, etc.). It runs quite well under wayland on my HP Omen 16 (R7 7840HS, RTX 4060). For some reasons it refused to start the game. I fixed it by copying the "Ubisoft Game Launcher" folder from AppData>Local from my Windows 11 installment to the corresponding folder. Next problem was, that the game would freeze on resuming save. I just copied the folder "ShaderByteCode" from Documents>My Games>Outlaws from the Windows 11 environment.
> > > > FPS are a little higher, I'd say 10 - 15 FPS more (baseline like 100 FPS under Windows 11). However, frame times seem to be better under Windows and graphics, too (DLSS3 + FG vs FSR3 + FG). Maybe it's just shader caching and will get better over time. I will try to run under X11, too.
> > > > Greetings
> > > > Edit:
> > > > I got the initial problems back again (with "product cannot be activated" at start and with the freezing on save load) even on Windows. I fixed it hopefully for longer by just reinstalling Ubisoft Connect in a different wine prefix. Still have to fix it on Windows. I guess Denuvo just checked my tinkering changes and disabled the game smh. Anyway game is now running on Wine 9.9, Vsync-off (with goverlay), FSR3+FG with a good frame rate.
> > > > I'm happy right now, wanted to ditch Windows 11 anyway. Only thing that I'm missing is the better upscaling quality with DLSS (I know I can activate it under Linux but without frame gen).
> > > 
> > > 
> > > Hello @sergeykern
> > > If you have time, could you give a bit of details of how you managed to make it run ? I have successfully build vkd3d-proton from this repo and how I have a bunch of files that I don't know exactly what to do 🤔
> > > Thanks in advance !
> > 
> > 
> > I am also asking nicely for some ELI5 directions, thanks :)
> 
> @makulski @N0ciple
> 
> I just got it working with Lutris! Works really well. Make sure to set Contact Shadows to Low for raytracing. I'm using a 4090.
> 
> I don't know if this the best way to it, but I'll explain how I did it.
> 
> 1. Get Lutris. I used Lutris from the official Arch repos.
> 2. Install Ubisoft Connect via Lutris' option on the sidebar, login, and install Outlaws.
> 3. Now you need to replace the two dlls(d3d12.dll and d3d12core.dll) for vkd3d-proton for both x86 and x64
> 4. Since this patch is merged into the master branch, pull master
> 5. Pull master with `git clone --recursive https://github.com/HansKristian-Work/vkd3d-proton`
> 6. Change to the directory you just pulled with `cd vkd3d-proton`
> 7. Build in your current directory with `./package-release.sh master ./ --no-package`
> 8. There's a new folder in your current folder called `vkd3d-proton-master`. Copy both dlls from the x86 and x64 folders into the respective Lutris folders for your chosen vkd3d-proton folders. For example, mine were in `/home/YOUR_HOME_DIRECTORY/.local/share/lutris/runtime/vkd3d/v2.12` with Lutris on Arch. I'm using the main Arch Lutris build, not a Flatpak if it exists.
> 9. Make sure to replace YOUR_HOME_DIRECTORY with your home directory's name.
> 10. Should be playable now!
> 
> Edit: Every time I reload the game after the first time it will lock up on the loading into game screen unless I delete my /home/YOU_HOME_FOLDER/Games/ubisoft-connect/GLCache folder before loading the game.

Got it working following this. The only problem I get is my Xbox One controller (or any controller for that matter) does not get detected by the game. :(

**Comment by SiriusStevas** [comment]
> > 1. Get Lutris. I used Lutris from the official Arch repos.
> > 2. Install Ubisoft Connect via Lutris' option on the sidebar, login, and install Outlaws.
> > 3. Now you need to replace the two dlls(d3d12.dll and d3d12core.dll) for vkd3d-proton for both x86 and x64
> > 4. Since this patch is merged into the master branch, pull master
> > 5. Pull master with `git clone --recursive https://github.com/HansKristian-Work/vkd3d-proton`
> > 6. Change to the directory you just pulled with `cd vkd3d-proton`
> > 7. Build in your current directory with `./package-release.sh master ./ --no-package`
> > 8. There's a new folder in your current folder called `vkd3d-proton-master`. Copy both dlls from the x86 and x64 folders into the respective Lutris folders for your chosen vkd3d-proton folders. For example, mine were in `/home/YOUR_HOME_DIRECTORY/.local/share/lutris/runtime/vkd3d/v2.12` with Lutris on Arch. I'm using the main Arch Lutris build, not a Flatpak if it exists.
> > 9. Make sure to replace YOUR_HOME_DIRECTORY with your home directory's name.
> > 10. Should be playable now!
> > 
> > Edit: Every time I reload the game after the first time it will lock up on the loading into game screen unless I delete my /home/YOU_HOME_FOLDER/Games/ubisoft-connect/GLCache folder before loading the game.
> 
> Got it working following this. The only problem I get is my Xbox One controller (or any controller for that matter) does not get detected by the game. :(

Hey, you could try to connect controller after the game has already launched. It helped me,  my steam controller works great

**Comment by schlatrice** [comment]
> Hey, you could try to connect controller after the game has already launched. It helped me, my steam controller works great

At first, I thought I already tried that, but then I understood you meant after loading a save and not just in the main menu as I had tried. Thank you very much, this did it for me :)

**Comment by ibanezbass** [comment]
> > > It appears that devs at Ubisoft forgot how to make scene lightning and post-process and put it all on RT.
> > 
> > 
> > He seems that Outlaws and Avatar are games that use RT only... There are not rasterization path so what you explain is expected behavior when disable rt...
> 
> From what I understand, the game uses software ray tracing as a fallback for GPUs that don't support hardware ray tracing. I don't know if this kicks in when you have it set to "low" or if it's actually only available on older cards. Is there a way to disable RT on RDNA2 or RDNA3 GPUS, for example, to test this? I know it used to be disabled by default in RADV when it was still being tested. Is there a way to disable it to see how the fallback performs?

VKD3D_CONFIG=nodxr

Just tested on my Legion GO running Bazzite and it seems to make no difference.

**Comment by shootie22** [comment]
I think the issue for crashing after loading in is having VSync on 😐  
  
I read through the whole thread, and the behavior I was experiencing was very similar to most people here. I followed the steps provided by [TheWiseNoob](https://github.com/TheWiseNoob) and I was able to play for over 3 hours without crashing. 
  
Afterwards, I must've messed with the video settings and turned VSync on because I started consistently crashing less than a minute after the gameplay loaded. I now turned off VSync and I've been playing for about 30 minutes with no crashes now.   
  
Hoping really hard I'm not jinxing it.

Nobara 40, Nvidia 560.35.03, Wayland, RTX 2070 Mobile, i7 9750H, KDE, 3x 1080p displays at different refresh rates.

**Comment by joshleblanc** [comment]
I haven't been following the thread but I think it's really important to note that outlaws has crashing issues on windows that are unresolved. There's a nonzero chance any crashes are actually a defect in the game.

**Comment by tajeraich** [comment]
> > > > It appears that devs at Ubisoft forgot how to make scene lightning and post-process and put it all on RT.
> > > 
> > > 
> > > He seems that Outlaws and Avatar are games that use RT only... There are not rasterization path so what you explain is expected behavior when disable rt...
> > 
> > 
> > From what I understand, the game uses software ray tracing as a fallback for GPUs that don't support hardware ray tracing. I don't know if this kicks in when you have it set to "low" or if it's actually only available on older cards. Is there a way to disable RT on RDNA2 or RDNA3 GPUS, for example, to test this? I know it used to be disabled by default in RADV when it was still being tested. Is there a way to disable it to see how the fallback performs?
> 
> VKD3D_CONFIG=nodxr
> 
> Just tested on my Legion GO running Bazzite and it seems to make no difference.

I've also tested and still got crashes when I turned ray tracing above low on my Ryzen 7 7800X3D / RX 7900 XTX desktop. With all ray tracing settings on low, I get stable gameplay.

**Comment by tajeraich** [comment]
> I think the issue for crashing after loading in is having VSync on 😐
> 
> I read through the whole thread, and the behavior I was experiencing was very similar to most people here. I followed the steps provided by [TheWiseNoob](https://github.com/TheWiseNoob) and I was able to play for over 3 hours without crashing.
> 
> Afterwards, I must've messed with the video settings and turned VSync on because I started consistently crashing less than a minute after the gameplay loaded. I now turned off VSync and I've been playing for about 30 minutes with no crashes now.
> 
> Hoping really hard I'm not jinxing it.
> 
> Nobara 40, Nvidia 560.35.03, Wayland, RTX 2070 Mobile, i7 9750H, KDE, 3x 1080p displays at different refresh rates. Proton-GE 9.13, using [these vkd3d dlls](https://github.com/realbardia/vkd3d-proton/releases/tag/starwars_outlaws_fix2) from an earlier comment in here.

I've had vsync on with no problem and don't get crashes, but I'm using an AMD GPU. There may be a specific issue with vsync on Nvidia.

**Comment by revan1611** [comment]
> > I think the issue for crashing after loading in is having VSync on 😐
> 
> > 
> 
> > I read through the whole thread, and the behavior I was experiencing was very similar to most people here. I followed the steps provided by [TheWiseNoob](https://github.com/TheWiseNoob) and I was able to play for over 3 hours without crashing.
> 
> > 
> 
> > Afterwards, I must've messed with the video settings and turned VSync on because I started consistently crashing less than a minute after the gameplay loaded. I now turned off VSync and I've been playing for about 30 minutes with no crashes now.
> 
> > 
> 
> > Hoping really hard I'm not jinxing it.
> 
> > 
> 
> > Nobara 40, Nvidia 560.35.03, Wayland, RTX 2070 Mobile, i7 9750H, KDE, 3x 1080p displays at different refresh rates. Proton-GE 9.13, using [these vkd3d dlls](https://github.com/realbardia/vkd3d-proton/releases/tag/starwars_outlaws_fix2) from an earlier comment in here.
> 
> 
> 
> I've had vsync on with no problem and don't get crashes, but I'm using an AMD GPU. There may be a specific issue with vsync on Nvidia. 

I don't think it's Nvidia related. I was playing with V-Sync on and was able to play for a good amount of hours. Now after Imp station heist I get crashes/freezes again with or without V-Sync on Nvidia. 

I think it has something to do with Shader caching and level preloading, maybe? Another issue I find weird is that the game gives me a warning on Start Menu, that the game is installed on mechanical drive, which I find weird because it's installed on SSD.

**Comment by tajeraich** [comment]
> > > I think the issue for crashing after loading in is having VSync on 😐
> > 
> > 
> > > 
> > 
> > 
> > > I read through the whole thread, and the behavior I was experiencing was very similar to most people here. I followed the steps provided by [TheWiseNoob](https://github.com/TheWiseNoob) and I was able to play for over 3 hours without crashing.
> > 
> > 
> > > 
> > 
> > 
> > > Afterwards, I must've messed with the video settings and turned VSync on because I started consistently crashing less than a minute after the gameplay loaded. I now turned off VSync and I've been playing for about 30 minutes with no crashes now.
> > 
> > 
> > > 
> > 
> > 
> > > Hoping really hard I'm not jinxing it.
> > 
> > 
> > > 
> > 
> > 
> > > Nobara 40, Nvidia 560.35.03, Wayland, RTX 2070 Mobile, i7 9750H, KDE, 3x 1080p displays at different refresh rates. Proton-GE 9.13, using [these vkd3d dlls](https://github.com/realbardia/vkd3d-proton/releases/tag/starwars_outlaws_fix2) from an earlier comment in here.
> > 
> > 
> > I've had vsync on with no problem and don't get crashes, but I'm using an AMD GPU. There may be a specific issue with vsync on Nvidia.
> 
> I don't think it's Nvidia related. I was playing with V-Sync on and was able to play for a good amount of hours. Now after Imp station heist I get crashes/freezes again with or without V-Sync on Nvidia.
> 
> I think it has something to do with Shader caching and level preloading, maybe? Another issue I find weird is that the game gives me a warning on Start Menu, that the game is installed on mechanical drive, which I find weird because it's installed on SSD.

I get the exact same message about the SSD. I also noticed that I can't switch from "Exclusive Fullscreen," but you can do switch to Borderless on Windows. There are definitely some issues with the game where they seem to have put Windows-specific checks in it.

**Comment by revan1611** [comment]
> > > > I think the issue for crashing after loading in is having VSync on 😐
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > I read through the whole thread, and the behavior I was experiencing was very similar to most people here. I followed the steps provided by [TheWiseNoob](https://github.com/TheWiseNoob) and I was able to play for over 3 hours without crashing.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Afterwards, I must've messed with the video settings and turned VSync on because I started consistently crashing less than a minute after the gameplay loaded. I now turned off VSync and I've been playing for about 30 minutes with no crashes now.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Hoping really hard I'm not jinxing it.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Nobara 40, Nvidia 560.35.03, Wayland, RTX 2070 Mobile, i7 9750H, KDE, 3x 1080p displays at different refresh rates. Proton-GE 9.13, using [these vkd3d dlls](https://github.com/realbardia/vkd3d-proton/releases/tag/starwars_outlaws_fix2) from an earlier comment in here.
> 
> > > 
> 
> > > 
> 
> > > I've had vsync on with no problem and don't get crashes, but I'm using an AMD GPU. There may be a specific issue with vsync on Nvidia.
> 
> > 
> 
> > I don't think it's Nvidia related. I was playing with V-Sync on and was able to play for a good amount of hours. Now after Imp station heist I get crashes/freezes again with or without V-Sync on Nvidia.
> 
> > 
> 
> > I think it has something to do with Shader caching and level preloading, maybe? Another issue I find weird is that the game gives me a warning on Start Menu, that the game is installed on mechanical drive, which I find weird because it's installed on SSD.
> 
> 
> 
> I get the exact same message about the SSD. I also noticed that I can't switch from "Exclusive Fullscreen," but you can do switch to Borderless on Windows. There are definitely some issues with the game where they seem to have put Windows-specific checks in it.

Weird, on my end it's Borderless by default, and I haven't changed it.

**Comment by joshleblanc** [comment]
> I haven't been following the thread but I think it's really important to note that outlaws has crashing issues on windows that are unresolved. There's a nonzero chance any crashes are actually a defect in the game.

Looks like people are actually using this repo to fix the windows crashes too. https://www.reddit.com/r/StarWarsOutlaws/comments/1fbcrrw/pc_random_crash_to_desktop_fix/

**Comment by revan1611** [comment]
Just reporting in:

- I completely removed the game and Ubisoft Connect and their prefixes. Re-Installed again through Lutris with Proton-GE-9.13 with just one environment variable `libglesv2=d`, nothing else. Haven't removed GLCache nor set env variable for prohibiting GL caching.
- I ran the game, entered the settings, and changed Upscaling method to **Fixed** (so it doesn't go beyond my resolution) and set frame limiter to **90** (for matching target framerate) and turned off V-Sync.
- Exited the game to save and cloud sync and entered again. I was able to play for straight 3 hours without any crashes whatsoever.
- Exited and entered the game again, and still no crashes happened. 

Previously the game would crash/froze after one minute approximately after walking a bit, which now for some reason doesn't happen anymore. I can only speculate that probably Upscaling and framerate limit had to do something about it.

**Comment by sergeykern** [comment]
> > I haven't been following the thread but I think it's really important to note that outlaws has crashing issues on windows that are unresolved. There's a nonzero chance any crashes are actually a defect in the game.
> 
> Looks like people are actually using this repo to fix the windows crashes too. https://www.reddit.com/r/StarWarsOutlaws/comments/1fbcrrw/pc_random_crash_to_desktop_fix/

I presumably finally fixed the game crashes for me. Could play for over half an hour on EndevourOS and even could load saves consistently even with DLSS and "DLSS FG" on (-> DLSS-to-FSR mod - DLSS-enabler, dlss as upscaler, auto as generator, Vulkan-hacks: true). Game is still crashing sometimes with DLSS rayrecon, so I play with it disabled for now.

Fix (at least for me): 

1) download vkd3d from: https://github.com/HansKristian-Work/vkd3d-proton/actions/runs/10724372560
2) make folder like "vkd3d-outlaws-fix" or smth like that under file path "/home/your_user/.local/share/lutris/runtime/vkd3d/" or whereever you'd have your vkd3d-folder.
3) under lutris configuration set vkd3d-runtime to "vkd3d-outlaws-fix" or however you've named it.
4) download dxvk from: https://github.com/doitsujin/dxvk/actions/runs/10708028008
5) copy dxgi from dxvk archive (x64) to "/home/your_user/.local/share/lutris/runtime/vkd3d/vkd3d-outlaws-fix/x64"
6) maybe optional (or the actual fix idk): run the sh-file in "/home/your_user/.local/share/lutris/runtime/vkd3d/vkd3d-outlaws-fix" by making it executable and opening terminal and then "./setup_vkd3d_proton.sh install". This will replace the files in system32 folder by the ones in x64 and x86 subfolders. Caution: idk if it could cause problems with other games since it seems that this file changes are made on wine-prefix-level.

Greetings

**Comment by ryzendew** [comment]
Tried everything here and still freezes on going in game

**Comment by MRo606** [comment]
> Tried everything here and still freezes on going in game
> 
> ![image](https://private-user-images.githubusercontent.com/84041391/366582833-62586951-e417-4507-8dda-556917db3067.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0Njg4NTUsIm5iZiI6MTcyNjQ2ODU1NSwicGF0aCI6Ii84NDA0MTM5MS8zNjY1ODI4MzMtNjI1ODY5NTEtZTQxNy00NTA3LThkZGEtNTU2OTE3ZGIzMDY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDA2MzU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMDFjMzhkODA4M2UxYzQ5ODk3NDhjMWE1OWRlOTU4NWE0YzgzMTNhYzVhOTA5NjhhYjg2NmQ3YmZkODZjODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x8TJoksfUehdAoteL83Y8cqK21dkIlYpgJ9nM2ovKP0)

I have a 7900 XTX and had this issue (freezing while trying to make a new game).
I fixed it by switching to amdvlk instead of vulkan-radeon.

But since then I updated proton-ge to fix some artifact with raytracing and tried back vulkan-radeon, and it didn't crash...

**Comment by RickS-C137** [comment]
> > I presumably finally fixed the game crashes for me. Could play for over half an hour on EndevourOS and even could load saves consistently even with DLSS and "DLSS FG" on (-> DLSS-to-FSR mod - DLSS-enabler, dlss as upscaler, auto as generator, Vulkan-hacks: true). Game is still crashing sometimes with DLSS rayrecon, so I play with it disabled for now.
> > Fix (at least for me):
> > ```
> > 1. download vkd3d from: https://github.com/HansKristian-Work/vkd3d-proton/actions/runs/10724372560
> > 
> > 2. make folder like "vkd3d-outlaws-fix" or smth like that under file path "/home/your_user/.local/share/lutris/runtime/vkd3d/" or whereever you'd have your vkd3d-folder.
> > 
> > 3. under lutris configuration set vkd3d-runtime to "vkd3d-outlaws-fix" or however you've named it.
> > 
> > 4. download dxvk from: https://github.com/doitsujin/dxvk/actions/runs/10708028008
> > 
> > 5. copy dxgi from dxvk archive (x64) to "/home/your_user/.local/share/lutris/runtime/vkd3d/vkd3d-outlaws-fix/x64"
> > 
> > 6. maybe optional (or the actual fix idk): run the sh-file in "/home/your_user/.local/share/lutris/runtime/vkd3d/vkd3d-outlaws-fix" by making it executable and opening terminal and then "./setup_vkd3d_proton.sh install". This will replace the files in system32 folder by the ones in x64 and x86 subfolders. Caution: idk if it could cause problems with other games since it seems that this file changes are made on wine-prefix-level.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Greetings
> 
> This fix worked for me on OpenSUSE Tumbleweed. I believe I didn't have to run the setup file in the vkd3d folder. Lutris runner options for me are:
> 
> Wine version: GE-Proton9-13 DXVK version: dxvk-outlaws-fix VKD3D version: vkd3d-outlaws-fix
> 
> In the game I didn't enable any raytracing. Using an NVidia GPU, currently on Driver Version: 550.107.02 and CUDA Version: 12.4
> 
> Thanks for the write up 👍 !
> 
> Note: I am still having _some_ issues, where after quitting the game and relaunching it, often it freezes when loading the game, past the main menu and it requires a system reboot, but overall it loads fine and runs fine.

I tried that, but the game still crashes in the loading screen. Tried to fiddle around with the settings, but that didn't change a thing. 
There are crashes to desktop for a lot of windows users as well, including me. So this game is sort of borked. That's sad, cause I really would like to play it.

**Comment by r0fld4nc3** [comment]
> I tried that, but the game still crashes in the loading screen. Tried to fiddle around with the settings, but that didn't change a thing. There are crashes to desktop for a lot of windows users as well, including me. So this game is sort of borked. That's sad, cause I really would like to play it.

Yes I totally feel you. It's still not perfect for me. It still stutters a bit and recently is more prone to crashing for some reason, it didn't happen about 1.5 weeks ago. So it's still kind of cursed but _sometimes_ it allows me to play...

**Comment by RickS-C137** [comment]
> > I tried that, but the game still crashes in the loading screen. Tried to fiddle around with the settings, but that didn't change a thing. There are crashes to desktop for a lot of windows users as well, including me. So this game is sort of borked. That's sad, cause I really would like to play it.
> 
> Yes I totally feel you. It's still not perfect for me. It still stutters a bit and recently is more prone to crashing for some reason, it didn't happen about 1.5 weeks ago. So it's still kind of cursed but _sometimes_ it allows me to play...

There's a patch announced for tomorrow which focuses on bug fixing, especially for the PC build. On the one hand I hope it changes something, on the other hand are the crashes still in Avatar, which uses the same engine. So it looks like either they don't care about it or they don't know the origin of it.

**Comment by nex86** [comment]
Game is still broken.
I tried the fix above, it does not work.
my video driver crashes and I have to hard reset the computer.

**Comment by Xephier102** [comment]
> > > I tried that, but the game still crashes in the loading screen. Tried to fiddle around with the settings, but that didn't change a thing. There are crashes to desktop for a lot of windows users as well, including me. So this game is sort of borked. That's sad, cause I really would like to play it.
> > 
> > 
> > Yes I totally feel you. It's still not perfect for me. It still stutters a bit and recently is more prone to crashing for some reason, it didn't happen about 1.5 weeks ago. So it's still kind of cursed but _sometimes_ it allows me to play...
> 
> There's a patch announced for tomorrow which focuses on bug fixing, especially for the PC build. On the one hand I hope it changes something, on the other hand are the crashes still in Avatar, which uses the same engine. So it looks like either they don't care about it or they don't know the origin of it.

If it's a patch for the game itself, expect nothing if you're on Linux. Most corporations refuse to even acknowledge that Linux exists cuz they ain't getting payouts like they are from M$ or CrApple.

**Comment by Xephier102** [comment]
> > I haven't been following the thread but I think it's really important to note that outlaws has crashing issues on windows that are unresolved. There's a nonzero chance any crashes are actually a defect in the game.
> 
> Looks like people are actually using this repo to fix the windows crashes too. https://www.reddit.com/r/StarWarsOutlaws/comments/1fbcrrw/pc_random_crash_to_desktop_fix/

This is why I don't get stoked over any new games anymore. Cuz even if they aren't loaded down with microtransactions and just complete garbage in general, they don't even work at all. Games are such a scam these days.. Video games used to = fun, now they = frustration, headache, scam, shortcut to a gambling addiction, pseudo-virus.. and WE pay THEM for this.. Capitalism is a joke..

**Comment by Dwarsen** [comment]
So, the game has now released on steam (thread here https://github.com/ValveSoftware/Proton/issues/8261) and this issue still persists. The workaround to delete the shader cache folders also seems to not work on the steam version, can anyone help with why? It seems like the GLCache folder does not exist on proton prefixes, perhaps it is handled differently?

**Comment by lordbasimore** [comment]
Now, since vkd3d-proton-2.13-9-ff1286f is available, it works even in Bottles. Ultra Settings (but RTX Direct Lighting off, as the default in this preset), DLSS on, Ray-Reconstruction on, FrameGen on. All fine. Bottles-Settings: Proton Experimental - dxvk-2.5.1 - vkd3d-proton-2.13-9-ff1286f - dxvk-nvapi-v0.7.1. BUT: To prevent the load-savegame-freezes you have to delete the content in .../"whatever-bottles-folder-you-have"/Ubisoft-Connect/cache/gl-shader/GLCache/ before each start of the game (same as in Lutris). In Steam it still doesn't work because of the savegame-load-freezes.

**Comment by Dwarsen** [comment]
> Now, since vkd3d-proton-2.13-9-ff1286f is available, it works even in Bottles. Ultra Settings (but RTX Direct Lighting off, as the default in this preset), DLSS on, Ray-Reconstruction on, FrameGen on. All fine. Bottles-Settings: Proton Experimental - dxvk-2.5.1 - vkd3d-proton-2.13-9-ff1286f - dxvk-nvapi-v0.7.1. BUT: To prevent the load-savegame-freezes you have to delete the content in .../"whatever-bottles-folder-you-have"/Ubisoft-Connect/cache/gl-shader/GLCache/ before each start of the game (same as in Lutris). In Steam it still doesn't work because of the savegame-load-freezes.

It really would be nice to know where the equivalent of that folder is in steam...surely someone knows? :)

**Comment by Dwarsen** [comment]
So I tried to use __GL_SHADER_DISK_CACHE=0 or __GL_SHADER_DISK_CACHE_PATH="a path on my disk" and in the latter case I did get a folder called GLCache that was populated with files.

In both cases I could also load my saves fine even on high settings no problem, first time every time. This is different from what happens otherwise where I am forced to fiddle with the settings to even get a save to load without freezing. However, the game will still freeze 5-10 seconds into the game regardless, so I'm wondering if there is something else as well...

Before each run I also removed the shader cache folders in the Outlaws directory and the vkd3d-proton shader file.

**Comment by lordbasimore** [comment]
I tried the aforementioned workarounds on my end.

The Env __GL_SHADER_DISK_CACHE=0 doesn't work for me. You could start a new game, but the game freezes right after loading a savegame / hitting the continue button.

The Env __GL_SHADER_DISK_CACHE_PATH="XYZ" at first seemed to work. You could start a new game. The GLCache folder was populated. I deleted it's content each time before launching the game again trying to load a savegame / continue. After some  attempts to load a savegame the game freezes again. 

I then tried it deleting the content of the following folders the same time before launching the game:

/XYZ/GLCache
/XYZ/SteamLibrary/steamapps/shadercache/
/XYZ/SteamLibrary/steamapps/compatdata/2842040/pfx/drive_c/users/steamuser/Documents/My Games/Outlaws/ShaderCache/
/XYZ/SteamLibrary/steamapps/compatdata/2842040/pfx/drive_c/users/steamuser/Documents/My Games/Outlaws/ShaderByteCode/

But it still crashed. Not in all cases immediately, but at least the third or fourth time loading a savegame.

In Lutris and Bottles these workarounds do work!

In Steam, this Game is cursed!

**Comment by Dwarsen** [comment]
@HansKristian-Work @doitsujin any leads here, anything we can provide/do to figure out why the workaround doesn't work on Steam but does outside? Or better yet of course, figure out why it happens in the first place... :)

**Comment by HansKristian-Work** [comment]
I made an attempt here: https://github.com/HansKristian-Work/vkd3d-proton/pull/2246

Hopefully that works.

**Comment by Dwarsen** [comment]
> I made an attempt here: #2246
> 
> Hopefully that works.
> 
> VKD3D_CONFIG=nodxr also seems to work around it ...

I'll try to figure out how to compile this locally and try it out, thanks :)

**Comment by Blisto91** [comment]
You can download a precompiled build here https://github.com/HansKristian-Work/vkd3d-proton/actions/runs/12201080683

**Comment by lordbasimore** [comment]
> VKD3D_CONFIG=nodxr also seems to work around it ...

Yes, this works - how cool is that?!

**Comment by HansKristian-Work** [comment]
Replace `~/.local/share/Steam/steamapps/common/Proton\ -\ Experimental/files/lib64/wine/vkd3d-proton/d3d12core.dll`

You might have to chmod +w it first.

> Doesn't this force a fallback to software RT though?

Yes, it's not an ideal workaround since you use ray-tracing.

**Comment by Dwarsen** [comment]
It seems to do the trick!

I maxed out everything and activated Ray Reconstruction, then loaded a save and it loaded with a hitch. Ran around a little bit, then quit the game and restarted a few times and did the same thing. No freezes! So knock on wood, it seems to work...!

**Comment by lordbasimore** [comment]
It seems to work!

I removed the EnV VKD3D_CONFIG=nodxr. Then I replaced the DLLs as in the instruction. Loaded my savegames several times. Tinkered with all the graphics settings (DLSS, Ray Reconstruction, RTX Direct Lighting, Ultra Setting etc. And it never freezed! Loading savegames is much faster now than before. Only thing left is the notification "It seems you have installed this game on an HDD..." (what I have not, it's an NVME). But that's a minor issue! So I'm looking forward having a great gaming weekend! 

Thank you all!
