### ISSUE TITLE
Monster Hunter Wilds: Crash after RE Engine splash screen

### ISSUE THREAD

**Issue by CreatureDev** [HansKristian-Work/vkd3d-proton#2182]
After compiling shaders and making it through the RE Engine splash screen the game crashes with the following error

Assertion failed!

File: ./src-wine/dlls/winevulkan/loader_thunks.c
Line: 5772

Expression: "!status && "vkLatencySleepNV""

### Software information
Monster Hunter Wilds Beta
proton bleeding-edge

### System information
- GPU: RTX 4070
- Driver: 550
- VKD3D-Proton version: master

I can gather the logs if necessary

**Comment by mbriar** [comment]
Does it work with `VKD3D_DISABLE_EXTENSIONS=VK_NV_low_latency2`? Just post the logs as well, it takes 2 seconds.

**Comment by CreatureDev** [comment]
That fixed it, thanks
For some reason the log file produced was over 450 MB

**Comment by mbriar** [comment]
>  For some reason the log file produced was over 450 MB
even huge logs usually compress to almost nothing if you zip them up.

**Comment by Blisto91** [comment]
This is a driver issue that i can't recall at the moment if the fix is included with the 560 versions or not. Should work with the latest dev betas and 565 at least.

**Comment by Blisto91** [comment]
Note that i just assume it is the same issue as Dragons Dogma 2 had which was fixed. It is possible there could be another so if any hit this with the drivers mentioned above do tell.

**Comment by ryzendew** [comment]
[steam-3065170.log](https://github.com/user-attachments/files/17592580/steam-3065170.log)
my crash with 565 beta drivers 

```
VKD3D_DISABLE_EXTENSIONS=VK_NV_low_latency2 PROTON_LOG=1 %command%
```

**Comment by ryzendew** [comment]
https://github.com/HansKristian-Work/vkd3d-proton/commit/dd7ad6d2545cb79a27f907d8512c4f1c1520c24f Use this commit to get the game working on nvidia 

![image](https://github.com/user-attachments/assets/e127b5e7-1392-4dbe-9bfa-99c496125422)

**Comment by ShadowDrakken** [comment]
Still an issue for some systems (Steam thread going on about it), myself included. Using Proton Experimental [bleeding edge]

Lenovo Legion 7i gen 9
Intel Core i9-14900HX
NVIDIA GeForce RTX 4070 Laptop GPU 8GB GDDR6
ZorinOS 17.2
Linux 6.8.0-48-generic x86_64
nvidia-driver-560/jammy,now 560.35.03-0ubuntu0~gpu22.04.4 amd64

Working fine on two other systems in the house though, an Intel laptop with a GTX1650 and an Intel desktop with a GTX3060. The only other substantial difference, and I don't know if this even matters, is that the laptop that's failing has SecureBoot enabled while the other two don't.

**Comment by Blisto91** [comment]
Note that the original problem for this issue is specifically about the below error before it gets too confusing
```
Assertion failed!

File: ./src-wine/dlls/winevulkan/loader_thunks.c
Line: 5772

Expression: "!status && "vkLatencySleepNV""
```

**Comment by ryzendew** [comment]
https://youtu.be/iEwbpi9ufAA?t=2983 GFX issues

Tried with Disabled up-scaling and lowest graphics also 
[steam-3065170.zip](https://github.com/user-attachments/files/17595831/steam-3065170.zip)
here is the log

**Comment by tvgold42** [comment]
Currently running into a different issue, using GE [9-17](https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/GE-Proton9-17) that has the latest git commit, using Nvidia 565.
Main issue is LOD problems, random walls of sand that are 1 px thick with no colision, and no ground will load correctly around you if you move at all. screenshot linked to below
https://imgur.com/a/7XbGotH

**Comment by tvgold42** [comment]
> That should probably be reported separately, though I'm also experiencing that.

Thanks for letting me know, made a separate issue here, happy to move the conversation on this specific issue over there

**Comment by ShadowDrakken** [comment]
> Currently running into a different issue, using GE [9-17](https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/GE-Proton9-17) that has the latest git commit, using Nvidia 565. Main issue is LOD problems, random walls of sand that are 1 px thick with no colision, and no ground will load correctly around you if you move at all. screenshot linked to below https://imgur.com/a/7XbGotH

the holes in the ground and walls of sand are caused by the Surface Quality setting (only accessible from the main menu, not once you load into the game). Setting it to Low resolves the issue (at least for a bit, it will slowly start glitching over time still)

**Comment by LueKely** [comment]
Currently having the same issues as well with the new update

`Assertion failed!
Line: 5953
Expression: "!status && "vkLantencySleepNV"" 
`

using `VKD3D_DISABLE_EXTENSIONS=VK_NV_low_latency2` hasn't solve this issue

specs:
cpu:  ryzen 5 5600g
gpu: rtx 3060 (12gb version)
os: Linux Mint 22.1
gpu driver: 550.12

**Comment by MescoMeso** [comment]
> Does it work with `VKD3D_DISABLE_EXTENSIONS=VK_NV_low_latency2`? Just post the logs as well, it takes 2 seconds.

how actually do this ?. I don't really understand and I got this issue in linux mint 22.1 now

thanks

**Comment by MescoMeso** [comment]
> [steam-3065170.log](https://github.com/user-attachments/files/17592580/steam-3065170.log) my crash with 565 beta drivers
> 
> ```
> VKD3D_DISABLE_EXTENSIONS=VK_NV_low_latency2 PROTON_LOG=1 %command%
> ```

where do you put that command ?. steam launch option ?

**Comment by raito-nkmr** [comment]
I can reproduce this issue with a much newer NVIDIA driver and current Proton 11.

### System information

* OS: Ubuntu 24.04
* Kernel: Linux 6.14.0-32-generic
* GPU: NVIDIA GeForce RTX 4060 Ti 8 GB
* NVIDIA driver: 580.159.03
* Vulkan API: 1.4.312
* Proton versions tested:

  * Proton 11.0-1
  * Proton Experimental 11.0-20260713
* Game: Monster Hunter Wilds, Steam AppID 2246340

### Symptoms

The game initially launched successfully, but crashed while using the character-creation preview mode where the character can be viewed from different angles.

After that, the game frequently crashed during startup at the same point. Occasionally it would launch once after Steam performed validation and shader processing, but the following launch would fail again.

The Proton log contains an `EXCEPTION_ACCESS_VIOLATION` (`0xc0000005`).

I tested the following without resolving the problem:

* Resetting `config.ini`
* Removing the game's `shader.cache2`
* Removing Steam's shader cache for AppID 2246340
* Removing `vkd3d-proton.cache`
* Recreating `compatdata/2246340`
* Switching between Proton Experimental and Proton 11.0-1

Using this launch option resolves the issue:

```text
VKD3D_DISABLE_EXTENSIONS=VK_NV_low_latency2 PROTON_LOG=1 %command%
```

With `VK_NV_low_latency2` disabled, I successfully launched the game twice consecutively. Without it, the first launch may occasionally succeed, but the next launch fails.

This appears to still affect NVIDIA driver 580.159.03 and Proton 11.0-1.

[monster-hunter-wilds-proton-logs-sanitized.zip](https://github.com/user-attachments/files/30266068/monster-hunter-wilds-proton-logs-sanitized.zip)
